CREATE DATABASE QuanLySinhVien;

USE QuanLySinhVien;

CREATE TABLE Class 
(
	ClassID 	INT 			NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ClassName 	VARCHAR(60) 	NOT NULL,
    StartDate	DATETIME		NOT NULL,
    Status		BIT
);

CREATE TABLE Student 
(
    StudentID 	INT 			NOT NULL AUTO_INCREMENT PRIMARY KEY,
    StudentName VARCHAR(30) 	NOT NULL,
    Address 	VARCHAR(50),
    Phone 		VARCHAR(20),
    Status 		BIT,
    ClassID 	INT 			NOT NULL
);

ALTER TABLE Student
	ADD FOREIGN KEY (ClassID) 	REFERENCES Class(ClassID);

CREATE TABLE Subject
(
	SubID		INT				NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SubNAME		VARCHAR(30)		NOT NULL,
    Credit		TINYINT			NOT NULL DEFAULT 1 CHECK ( Credit >= 1 ),
    Status		BIT				DEFAULT 1
);

CREATE TABLE Mark
(
	MarkID		INT				NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SubID		INT				NOT NULL UNIQUE,
    StudentID	INT				NOT NULL UNIQUE,
    Mark		FLOAT			DEFAULT 0 CHECK ( Mark BETWEEN 0 AND 100 ),
    ExamTimes	TINYINT			DEFAULT 1,
    FOREIGN KEY	(SubId) REFERENCES Subject	(SubID),
    FOREIGN KEY	(StudentID)	REFERENCES Student	(StudentID)
);